### ISSUE TITLE
Multiple files include "Rmt.h", but file is named "rmt.h"

### ISSUE THREAD

**Issue by TRIA** [Fundacio-i2CAT/rinasense#12]
Multiple files include "Rmt.h", but file is named "rmt.h".  This works on case-ignoring file systems, but not on case-significant file systems.  Files in question (in master):
srb@Silver rinasense % find-anywhere "\"Rmt.h\""
./components/IPCP/normalIPCP.c:#include "Rmt.h"
./components/EFCP/include/efcpStructures.h:#include "Rmt.h"
./components/EFCP/include/EFCP.h:#include "Rmt.h"
./components/EFCP/EFCP.c:#include "Rmt.h"
./components/EFCP/dtp.c:#include "Rmt.h"
./components/Rmt/du.c:#include "Rmt.h"
./components/Rmt/pci.c:#include "Rmt.h"
./components/Rmt/include/du.h:#include "Rmt.h"
./components/Rmt/Rmt.c:#include "Rmt.h"
(END)

file itself:
srb@Silver rinasense % find . -name rmt.h -print
./components/Rmt/include/rmt.h

**Comment by fdgonthier** [comment]
I have a patch for that in my linux branch.
