### ISSUE TITLE
Generalize PIDM, CEPIDM, and IPCPIDM

### ISSUE THREAD

**Issue by fdgonthier** [Fundacio-i2CAT/rinasense#14]
Because IRATI's PIDM and I have had some... disagreements ...in the past, I've took the time last week to see how hard it would be to replace the code that tracks the allocated ports by a semantically simpler bit array. 

It turns out the use of the bit array considerably simplifies the semantic of the PIDM code. It might consume an higher amount of memory but the memory it consumes always remains constant, preventing things such as memory fragmentation. That said, using 256 bytes to keep track of 2048 ports does not seem like a big deal in general.

After I had replaced the linked-list based PIDM by a bit array, I realized that the CEPID manager and the IPCPID manager were basically carbon copies of the PIDM code and replacing the use of linked lists in those code would lead to all 3 source file looking exactly the same.

I propose replaced the 3 manager objects by a generic integer allocator + tracker, using a bit array. Of course, this proposal might be moot if the code of the 3 manager objects are to be different but from what I see in the IPCP components of RinaSense, it does not appear to be the case. Steve also concurs.

While this proposal is meant for RinaSense first, it also could probably apply to IRATI.

I have pushed my bit array code on my own tree:

https://github.com/fdgonthier/rinasense/blob/linux/components/Common/include/bit_array.h

And the PIDM code using the bit array is here:

https://github.com/fdgonthier/rinasense/blob/linux/components/IPCP/pidm.c

This was put in the 'linux' branch to help my porting effort but I could probably take this change and adapt it to your tree.

**Comment by edugrasa** [comment]
Hi @fdgonthier , @esmaxness confirms that the 3 allocators would be the same, so let's go ahead with your proposal :)

**Comment by fdgonthier** [comment]
This has been merged as part of #57
