### ISSUE TITLE
Uncommented mystery block

### ISSUE THREAD

**Issue by fdgonthier** [Fundacio-i2CAT/rinasense#78]
I'm working on porting RINA_API to POSIX and I stumbled on this, which I cannot quite explain. This might have been done to silence a warning, but I'm worried that there might be some code missing.

https://github.com/Fundacio-i2CAT/rinasense/blob/0fa302ed84be0550de24f66330aeeca527f42e50/components/RINA_API/RINA_API.c#L530-L534

**Comment by esmaxness** [comment]
These lines were not properly merged during the pull master. It must not be there. So, I deleted that lines
