### ISSUE TITLE
Queue Failed

### ISSUE THREAD

**Issue by esmaxness** [Fundacio-i2CAT/rinasense#81]
It is not possible to enqueue a networkbuffer into the IPCP stack coming from the Network Interface.  It show this lines:

E [RsQueue]: mq_timedsend failed (errno: 0)
E [IPCP_MANAGER]: Failed to add message to IPCP queue (errno: 0)
E (5637) [NetInterface]: Failed to enqueue packet to network stack 0x3ffc904c, len 62

**Comment by fdgonthier** [comment]
Can you show me how to reproduce this with some simple test code?

**Comment by esmaxness** [comment]
These messages of failed appears when I call the RINA_IPCPInit().  An ARP request was sended during the shim flow allocation process. But when I got the ARP reply, this ARP packet can not be enqueue into the network stack.

#include "IPCP_api.h"

void app_main(void)
{
    RINA_IPCPInit();
}

**Comment by fdgonthier** [comment]
Alright. I'm currently stuck in some merge or rebase problem for some other patches I've made but I'll soon be able to send packets to the stack with Scapy. It'll probably happen some time next week. At that point, I should be able to inject an ARP packet in the stack without having to setup RINA.

**Comment by fdgonthier** [comment]
I've been able to inject an ARP packet in the stack using a very small Python program with Scapy. I'm going further than what you're seeing.

```
D [IPCP_MANAGER]: Ethernet packet of type 4305u: ACCEPTED
D [NetBuffer]: Free descriptor Count: 18
D [RsQueue]: Sent 16 byte(s) on /IPCPQueue
I [IPCP_MANAGER]: Packet to network stack 0x55fb7180ee00, len 48
I [IPCP_MANAGER]: ARP Packet Received
I [SHIM_WIFI]: CREATE GPA address: a|b|
I [SHIM_WIFI]: CREATE GPA size: 4
I [SHIM_WIFI]: CREATE GPA address: 
I [SHIM_WIFI]: CREATE GPA size: 4
I [ARP]: Looking for filler 0x00 in GPA (length = 4)
I [ARP]: GPA doesn't need to be shrinked ...
I [ARP]: Looking for filler 0x00 in GPA (length = 4)
I [ARP]: Shrinking GPA to 3
E [ARP]: ARP_REQUEST ptype 0x0100
I [ARP]: eARPLookupGPA loop start
I [ARP]: eARPLookupGPA loop: 0
I [ARP]: eARPLookupGPA loop: 1
I [ARP]: eARPLookupGPA loop: 2
I [ARP]: eARPLookupGPA loop: 3
E [ARP]: I don't have a table for ptype 0xF0D1
```

There were some problem in the ARP code but they were not related to what you're describing. This means a) the problem is already fixed my tree, or, b) the problem is ESP-specific in which case I can't quite reproduce the problem yet.

For a) -- I'll try to upload and make a PR out of my last changes.

**Comment by esmaxness** [comment]
I have fixed this issue by changing configurations in the RsQueue. Specific settings for ESP32 support
