### ISSUE TITLE
Confusion between master and dev

### ISSUE THREAD

**Issue by fdgonthier** [Fundacio-i2CAT/rinasense#97]
@edugrasa 

As of yesterday, 'master' is more current than 'dev'. Out of the last patches I've submitted, 2 have ended up in 'dev', which was then merged in 'master', where 2 more patches were added. This means 'dev' is no longer bleeding. If this is by-design, I would like to know so that I stop rebasing my work on 'dev'

Master:

![image](https://user-images.githubusercontent.com/557555/185637483-806c9b56-2dba-488d-a4d2-e8312c5c8932.png)

Dev: 

![image](https://user-images.githubusercontent.com/557555/185637588-810accb2-24a2-4c2b-a3b3-efdc07c310d6.png)

**Comment by edugrasa** [comment]
Hi François-Denis,

The idea is that master has the latest stable version, while dev is the bleeding edge. Now we don't have any stable version yet (hence master and dev will be the same), but pull request of new "features" should be merged into dev, tested there, and only when proved "stable" enough will be merged into master.
